document.write('<!-- 用来产生编辑状态的ActiveX控件的JS脚本-->   ');
document.write('<!-- 因为微软的ActiveX新机制，需要一个外部引入的js-->   ');
document.write('<object id="TANGER_OCX" classid="clsid:C9BC4DFF-4248-4a3c-8A49-63A7D317F404"    ');
document.write('codebase="officecontrol.cab#version=4,0,1,0" width="100%" height="100%">   ');
document.write('<param name="BorderStyle" value="1">   ');
document.write('<param name="BorderColor" value="14402205">   ');
document.write('<param name="TitlebarColor" value="15658734">   ');
document.write('<param name="TitlebarTextColor" value="0">   ');
document.write('<param name="Caption" value="天津建工工程总承包">   ');
document.write('<param name="IsUseUTF8URL" value="-1">   ');
document.write('<param name="IsUseUTF8DATA" value="-1">   ');
document.write('<param name="MaxUploadSize" value="10000000">   ');
document.write('<param name="MenubarColor" value="14402205">   ');
document.write('<param name="MenuButtonColor" VALUE="16180947">   ');
document.write('<param name="MenuBarStyle" value="3">   ');
document.write('<param name="MenuButtonStyle" value="7">   ');
document.write('<PARAM NAME="ProductCaption" VALUE="浪潮办公自动化系统"> ');
document.write('<PARAM NAME="ProductKey" VALUE="C4718A556E4782DA0D6842629CBDA9EA7E4E0D91">  ');
document.write('<PARAM NAME="MakerCaption" VALUE="浪潮集团山东通用软件有限公司">  ');
document.write('<PARAM NAME="MakerKey" VALUE="72EDB2139FB9C5FD0D061F279908F94CF70E7318">  ');
document.write('<SPAN STYLE="color:red">不能装载文档控件。请在检查浏览器的选项中检查浏览器的安全设置。</SPAN>   ');
document.write('</object>   ');